# Site/SEO settings
email: robert.weston1995@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Hazelwood Farm
title: Welcome to Hazelwood
description: >
  Welcome to Hazelwood farm. Come for the foccacia and stay for the crafts.
url: http://barber.samesies.io
twitter_username: 
default_img: /assets/images/seo.jpg
social:
  - name: instagram
    url: https://www.instagram.com/thomas.vaeth/ 

# Contact settings (this requires a mail chimp account)
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Rob Weston
    bio: 
    url: http://thomasvaeth.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Hazelwood Farm'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-include-cache
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

gems:
- jekyll-seo-tag
- jekyll-taglist
